# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.google_cloud_storage.service:
        class: \Google_Service_Storage
        factory_class: AppBundle\Factory\GoogleCloudStorageServiceFactory
        factory_method: 'createService'
        arguments:
            -
                # all the arguments needed like service account email and path to key.p12